import {
  createClient,
  type SupabaseClient,
} from "npm:@supabase/supabase-js@^2.58.0";

import { buildRepairPrompt, buildUserPrompt, SYSTEM_PROMPT } from "./prompt.ts";
import { createAnthropicProvider } from "./providers/anthropic.ts";
import { createOllamaProvider } from "./providers/ollama.ts";
import {
  type PlanProvider,
  type ProviderMessage,
  ProviderRefusal,
} from "./providers/types.ts";
import { sanitizeGeneratedText } from "./sanitize.ts";
import { isGeneratedPlan, PLAN_JSON_SCHEMA } from "./schema.ts";
import { resolveDays, unresolved, type ResolvedDay } from "./scripture.ts";

const CORS = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
};

const json = (body: unknown, status = 200) =>
  new Response(JSON.stringify(body), {
    status,
    headers: { ...CORS, "Content-Type": "application/json" },
  });

// Three, as the plan has said all along. One meant hitting the wall on your
// second plan — before you had a week of using the app to judge it by, and with
// no way to pay past it, since nothing writes `subscriptions` yet.
const FREE_PLAN_LIMIT = 3;
const MIN_DAYS = 3;
const MAX_DAYS = 30;

/**
 * Days per request. A whole 30-day plan in one call does not fit inside the
 * function's wall clock — it gets killed mid-flight and leaves the plan stuck.
 * Each stretch is generated by its own invocation, so each one starts with a
 * fresh time budget.
 */
const CHUNK_DAYS = 7;

/**
 * Work continues after the response is sent. The isolate still has a time
 * budget, which is exactly why a stretch has to be small enough to finish
 * inside it.
 */
const runInBackground = (promise: Promise<unknown>) => {
  const runtime = (
    globalThis as {
      EdgeRuntime?: { waitUntil?: (p: Promise<unknown>) => void };
    }
  ).EdgeRuntime;

  if (runtime?.waitUntil) {
    runtime.waitUntil(promise);
  } else {
    void promise;
  }
};

const selectProvider = (): PlanProvider => {
  const provider = Deno.env.get("AI_PROVIDER") ?? "anthropic";

  if (provider === "ollama") {
    return createOllamaProvider(
      Deno.env.get("OLLAMA_URL") ?? "http://host.docker.internal:11434",
      Deno.env.get("OLLAMA_MODEL") ?? "gemma3:4b",
    );
  }

  const apiKey = Deno.env.get("ANTHROPIC_API_KEY");

  if (!apiKey) {
    throw new Error(
      "ANTHROPIC_API_KEY is not set. Set it with `supabase secrets set`, " +
        "or use AI_PROVIDER=ollama for local development.",
    );
  }

  return createAnthropicProvider(apiKey);
};

type PlanRow = {
  id: string;
  owner_id: string;
  duration_days: number;
  start_date: string;
  status: string;
  source_prompt: {
    answers?: {
      /** Several since the onboarding went multi-select. */
      seasons?: string[];
      /** The single-season shape, kept so older rows still read. */
      season?: string;
      topics?: string[];
      gender?: string;
      custom_topic?: string;
      minutes?: number;
    };
  } | null;
};

type Visibility = "private" | "circles" | "link" | "public";

/**
 * How many fresh isolates the very first stretch gets before the plan is
 * declared failed.
 *
 * Later stretches already degrade well — a plan a few days short is far better
 * than one thrown away — but the first stretch is all-or-nothing: without it
 * there is no day to pray. The provider has already retried and already tried
 * the fallback model by the time we get here, so this is the outer ring: a new
 * isolate with a full wall clock, in case the problem was the isolate itself.
 */
const FIRST_CHUNK_ISOLATES = 3;

/** Asks this same function to write the next stretch, in a fresh isolate. */
const requestNextChunk = async (
  planId: string,
  authHeader: string,
  attempt = 1,
) => {
  try {
    await fetch(
      `${Deno.env.get("SUPABASE_URL")}/functions/v1/generate-prayer-plan`,
      {
        method: "POST",
        headers: {
          Authorization: authHeader,
          apikey: Deno.env.get("SUPABASE_ANON_KEY")!,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ continue_plan_id: planId, attempt }),
      },
    );
  } catch (error) {
    // The plan keeps the days it already has; the user can still pray today.
    console.error("could not schedule the next stretch", error);
  }
};

type ChunkArgs = {
  supabase: SupabaseClient;
  provider: PlanProvider;
  plan: PlanRow;
  displayName: string;
  fromDay: number;
  toDay: number;
  authHeader: string;
  attempt?: number;
};

const writeChunk = async ({
  supabase,
  provider,
  plan,
  displayName,
  fromDay,
  toDay,
  authHeader,
  attempt = 1,
}: ChunkArgs) => {
  const isFirstChunk = fromDay === 1;

  const fail = async (reason: string) => {
    // Only the first stretch can fail the whole plan. Later on the user
    // already has usable days, and throwing those away would be worse than a
    // plan that is a few days shorter than requested.
    if (!isFirstChunk) {
      console.error(`stretch ${fromDay}-${toDay} failed: ${reason}`);
      return;
    }

    // A refusal will not change on a retry, so it fails immediately; anything
    // else gets another isolate before we tell someone their plan is broken.
    if (reason !== "refused" && attempt < FIRST_CHUNK_ISOLATES) {
      console.warn(
        `first stretch failed (${reason}), isolate ${attempt}/${FIRST_CHUNK_ISOLATES}`,
      );
      await requestNextChunk(plan.id, authHeader, attempt + 1);
      return;
    }

    await supabase
      .from("prayer_plans")
      .update({ status: "failed", generation_error: reason })
      .eq("id", plan.id);
  };

  // Not a plain select: prayer_plan_days hides days whose unlock_date is in the
  // future, even from the owner, so a direct query would report only the days
  // already unlocked and the generator would rewrite the rest.
  const { data: existing } = await supabase.rpc("plan_written_days", {
    p_plan_id: plan.id,
  });

  const answers = plan.source_prompt?.answers ?? {};

  const userPrompt = buildUserPrompt({
    displayName,
    durationDays: plan.duration_days,
    // Plans written before the onboarding went multi-select carry a single
    // `season`; reading both keeps them generating as they always did.
    seasons: answers.seasons ?? (answers.season ? [answers.season] : []),
    topics: answers.topics ?? [],
    gender: answers.gender ?? null,
    customTopic: answers.custom_topic ?? null,
    minutes: answers.minutes ?? null,
    fromDay,
    toDay,
    previousDays: (existing ?? []) as {
      day_number: number;
      title: string;
      scripture_ref: string | null;
    }[],
  });

  const messages: ProviderMessage[] = [{ role: "user", content: userPrompt }];
  let result;

  try {
    result = await provider.generate({
      system: SYSTEM_PROMPT,
      messages,
      schema: PLAN_JSON_SCHEMA,
    });
  } catch (error) {
    console.error("generation failed", error);
    await fail(
      error instanceof ProviderRefusal ? "refused" : "generation_failed",
    );
    return;
  }

  if (result.usage) {
    // cache_read_input_tokens should be non-zero from the second stretch
    // onward. If it stays at zero something varies inside the system prompt,
    // and the per-user cost roughly triples.
    console.log(
      `stretch ${fromDay}-${toDay} · ${result.model} · in ${result.usage.input_tokens} ` +
        `out ${result.usage.output_tokens} · cache read ${result.usage.cache_read_input_tokens} ` +
        `write ${result.usage.cache_creation_input_tokens}`,
    );
  }

  let generated;

  try {
    generated = JSON.parse(result.json);
  } catch {
    await fail("invalid_model_output");
    return;
  }

  if (!isGeneratedPlan(generated) || generated.days.length === 0) {
    await fail("invalid_model_output");
    return;
  }

  // Scripture validation: the gate that keeps invented verses out. Anything
  // that does not resolve against the real RVR1909 text gets one repair
  // attempt; if it still fails the day ships WITHOUT a verse rather than with
  // a fabricated one.
  let days: ResolvedDay[] = await resolveDays(supabase, generated.days);
  let bad = unresolved(days);

  if (bad.length > 0) {
    console.warn(
      `unresolved references: ${bad
        .slice(0, 10)
        .map((d) => d.scripture_ref)
        .join(", ")}${bad.length > 10 ? ` (+${bad.length - 10} more)` : ""}`,
    );

    try {
      const repaired = await provider.generate({
        system: SYSTEM_PROMPT,
        messages: [
          ...messages,
          { role: "assistant", content: result.json },
          { role: "user", content: buildRepairPrompt(bad) },
        ],
        schema: PLAN_JSON_SCHEMA,
      });

      const repairedPlan = JSON.parse(repaired.json);

      if (isGeneratedPlan(repairedPlan)) {
        const rechecked = await resolveDays(supabase, repairedPlan.days);

        if (unresolved(rechecked).length < bad.length) {
          days = rechecked;
          bad = unresolved(days);
        }
      }
    } catch (error) {
      console.warn("repair pass failed; shipping without those verses", error);
    }
  }

  // The model is told which absolute day numbers to write, but its numbering is
  // not load-bearing: the slot a day occupies is decided here.
  const slotted = days.slice(0, toDay - fromDay + 1).map((day, index) => {
    const dayNumber = fromDay + index;
    const unlock = new Date(`${plan.start_date}T00:00:00Z`);
    unlock.setUTCDate(unlock.getUTCDate() + dayNumber - 1);

    return {
      plan_id: plan.id,
      day_number: dayNumber,
      title: sanitizeGeneratedText(day.title),
      // Canonical spelling from our own Bible table, not the model's.
      scripture_ref: day.canonical_ref,
      // Straight from the RVR1909 table, so it needs no cleaning.
      scripture_text: day.scripture_text,
      interpretation: sanitizeGeneratedText(day.interpretation),
      daily_action: sanitizeGeneratedText(day.daily_action),
      prayer_body: sanitizeGeneratedText(day.prayer_body),
      intercessor_prayer: sanitizeGeneratedText(day.intercessor_prayer),
      unlock_date: unlock.toISOString().slice(0, 10),
    };
  });

  const { error: daysError } = await supabase
    .from("prayer_plan_days")
    .insert(slotted);

  if (daysError) {
    console.error("could not save plan days", daysError);
    await fail("persist_failed");
    return;
  }

  const lastDay = fromDay + slotted.length - 1;
  const isComplete = lastDay >= plan.duration_days;

  if (isFirstChunk) {
    // Usable immediately: day 1 is ready even though later days are not.
    await supabase
      .from("prayer_plans")
      .update({
        title: (sanitizeGeneratedText(generated.title) ?? "").slice(0, 140),
        theme: sanitizeGeneratedText(generated.theme)?.slice(0, 140) ?? null,
        status: "active",
        source_prompt: {
          ...(plan.source_prompt ?? {}),
          model: result.model,
          provider: provider.name,
        },
      })
      .eq("id", plan.id);
  } else if (isComplete) {
    await supabase
      .from("prayer_plans")
      .update({ status: "active" })
      .eq("id", plan.id);
  }

  // Only continue while the stretch actually produced days, so a model that
  // returns nothing cannot spin this forever.
  if (!isComplete && slotted.length > 0) {
    await requestNextChunk(plan.id, authHeader);
  }
};

Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: CORS });
  }

  const authHeader = req.headers.get("Authorization");

  if (!authHeader) {
    return json({ error: "unauthorized" }, 401);
  }

  // Deliberately the user's client, not the service role: every write below
  // still passes through RLS, so a bug here cannot touch someone else's plan.
  const supabase = createClient(
    Deno.env.get("SUPABASE_URL")!,
    Deno.env.get("SUPABASE_ANON_KEY")!,
    { global: { headers: { Authorization: authHeader } } },
  );

  const {
    data: { user },
  } = await supabase.auth.getUser();

  if (!user) {
    return json({ error: "unauthorized" }, 401);
  }

  const body = await req.json().catch(() => ({}));

  let provider: PlanProvider;

  try {
    provider = selectProvider();
  } catch (error) {
    console.error("provider misconfigured", error);
    return json({ error: "provider_unavailable" }, 503);
  }

  const { data: profile, error: profileError } = await supabase
    .from("profiles")
    .select("display_name")
    .eq("id", user.id)
    .single();

  if (profileError) {
    console.error("could not read the caller's profile", profileError);
    return json({ error: "profile_unavailable" }, 500);
  }

  const displayName = profile?.display_name?.trim() || "esta persona";

  // --- Continuation: write the next stretch of an existing plan ------------
  if (typeof body?.continue_plan_id === "string") {
    const { data: plan } = await supabase
      .from("prayer_plans")
      .select("id, owner_id, duration_days, start_date, status, source_prompt")
      .eq("id", body.continue_plan_id)
      .maybeSingle();

    // RLS already limits this to plans the caller can read; the ownership check
    // makes sure a plan merely shared with them cannot be extended.
    if (!plan || plan.owner_id !== user.id) {
      return json({ error: "not_found" }, 404);
    }

    const { data: writtenDays } = await supabase.rpc("plan_written_days", {
      p_plan_id: plan.id,
    });

    const written = (writtenDays as unknown[] | null)?.length ?? 0;

    // The hard stop on runaway continuations: never write past the length the
    // plan was created with.
    if (written >= plan.duration_days) {
      return json({ status: "complete" });
    }

    const fromDay = written + 1;
    const toDay = Math.min(written + CHUNK_DAYS, plan.duration_days);

    runInBackground(
      writeChunk({
        supabase,
        provider,
        plan: plan as PlanRow,
        displayName,
        fromDay,
        toDay,
        authHeader,
        // Carried across isolates so the first stretch knows how many goes it
        // has already had; anything else is a fresh continuation.
        attempt:
          typeof body?.attempt === "number" ? Math.round(body.attempt) : 1,
      }),
    );

    return json({ plan_id: plan.id, from_day: fromDay, to_day: toDay }, 202);
  }

  // --- New plan ------------------------------------------------------------
  const durationDays =
    typeof body?.duration_days === "number"
      ? Math.round(body.duration_days)
      : 7;

  if (durationDays < MIN_DAYS || durationDays > MAX_DAYS) {
    return json(
      { error: "invalid_duration", min: MIN_DAYS, max: MAX_DAYS },
      400,
    );
  }

  // Generation is the expensive part, so it is what the paywall guards, and the
  // check lives here because the client can be lied to. Failed attempts do not
  // count against the allowance.
  const [{ count: planCount }, { data: subscription }] = await Promise.all([
    supabase
      .from("prayer_plans")
      .select("id", { count: "exact", head: true })
      .eq("owner_id", user.id)
      .neq("status", "failed"),
    supabase
      .from("subscriptions")
      .select("status, expires_at")
      .eq("user_id", user.id)
      .maybeSingle(),
  ]);

  const isSubscribed =
    subscription?.status === "active" &&
    (!subscription.expires_at ||
      new Date(subscription.expires_at) > new Date());

  // A circle's plan does not spend the personal allowance: it belongs to the
  // circle, and charging it to whoever runs the circle would punish exactly the
  // person holding it together. It stays bounded anyway — one active plan per
  // circle, enforced by a unique partial index.
  const isCirclePlan = typeof body?.group_id === "string";

  if (!isCirclePlan && !isSubscribed && (planCount ?? 0) >= FREE_PLAN_LIMIT) {
    return json({ error: "plan_limit_reached", limit: FREE_PLAN_LIMIT }, 402);
  }

  const { data: settings, error: settingsError } = await supabase
    .from("profile_settings")
    .select("onboarding_answers")
    .eq("id", user.id)
    .single();

  if (settingsError) {
    console.error("could not read the caller's settings", settingsError);
    return json({ error: "profile_unavailable" }, 500);
  }

  // The onboarding answers are the baseline; anything chosen for this specific
  // plan overrides them, which is what stops a second plan from reading like a
  // copy of the first.
  const onboarding = (settings?.onboarding_answers ?? {}) as Record<
    string,
    unknown
  >;

  const requestedTopics = Array.isArray(body?.topics)
    ? (body.topics as unknown[]).filter(
        (topic): topic is string => typeof topic === "string",
      )
    : null;

  const customTopic =
    typeof body?.custom_topic === "string"
      ? body.custom_topic.trim().slice(0, 200)
      : null;

  const answers = {
    ...onboarding,
    ...(requestedTopics?.length ? { topics: requestedTopics } : {}),
    ...(customTopic ? { custom_topic: customTopic } : {}),
  };

  const visibility: Visibility =
    body?.visibility === "circles" ||
    body?.visibility === "link" ||
    body?.visibility === "public"
      ? body.visibility
      : "private";

  // A circle's own plan: one shared walk everybody reads, rather than a
  // personal plan shared outward. `prayer_plans.group_id` has carried the
  // policies for it since the first migration with nothing ever writing it.
  const groupId = isCirclePlan ? (body!.group_id as string) : null;

  const circleIds = Array.isArray(body?.circle_ids)
    ? (body.circle_ids as unknown[]).filter(
        (id): id is string => typeof id === "string",
      )
    : [];

  if (visibility === "circles" && circleIds.length === 0) {
    return json({ error: "no_circles_selected" }, 400);
  }

  if (groupId) {
    // Admins only, and one active plan per circle. The unique partial index is
    // what actually enforces the second half — this check exists to answer with
    // something a screen can explain rather than a constraint violation.
    const { data: allowed } = await supabase.rpc("can_create_circle_plan", {
      p_group_id: groupId,
    });

    if (allowed !== true) {
      return json({ error: "circle_plan_not_allowed" }, 403);
    }
  }

  const startDate = new Date().toISOString().slice(0, 10);

  const { data: created, error: planError } = await supabase
    .from("prayer_plans")
    .insert({
      owner_id: user.id,
      title: "…",
      duration_days: durationDays,
      start_date: startDate,
      // 'circles' is an app-level concept; at the row level a plan shared with
      // circles is simply not private, and plan_shares says with whom. A
      // circle's *own* plan is the one case that does use 'group'. 'public' is
      // the one the row level does carry: it is what lets a plan sit on your
      // profile and be opened by somebody who has no link and shares no circle.
      visibility: groupId
        ? "group"
        : visibility === "link"
          ? "link"
          : visibility === "public"
            ? "public"
            : "private",
      group_id: groupId,
      status: "generating",
      generated_by: "ai",
      source_prompt: { answers },
    })
    .select("id, owner_id, duration_days, start_date, status, source_prompt")
    .single();

  if (planError || !created) {
    console.error("could not create plan row", planError);
    return json({ error: "persist_failed" }, 500);
  }

  if (visibility === "circles") {
    // RLS rejects a circle the caller does not belong to, so a bad id fails
    // here rather than silently sharing into someone else's circle.
    const { error: shareError } = await supabase.from("plan_shares").insert(
      circleIds.map((circleId) => ({
        plan_id: created.id,
        group_id: circleId,
        created_by: user.id,
      })),
    );

    if (shareError) {
      console.error("could not share with the chosen circles", shareError);
      await supabase.from("prayer_plans").delete().eq("id", created.id);
      return json({ error: "invalid_circles" }, 400);
    }
  }

  let shareToken: string | null = null;

  if (visibility === "link") {
    const { data: link } = await supabase
      .from("share_links")
      .insert({ scope: "plan", plan_id: created.id, created_by: user.id })
      .select("token")
      .single();

    shareToken = link?.token ?? null;
  }

  runInBackground(
    writeChunk({
      supabase,
      provider,
      plan: created as PlanRow,
      displayName,
      fromDay: 1,
      toDay: Math.min(CHUNK_DAYS, durationDays),
      authHeader,
    }),
  );

  return json(
    { plan_id: created.id, status: "generating", share_token: shareToken },
    202,
  );
});
